//! Library summaries: what a call to a *known* library function does with
//! its inputs, when the corpus does not define it.
//!
//! Without a summary, an unresolved call is modelled as "every input may
//! reach the result, and (in languages that pass by reference) every
//! argument may be written". That is the sound default and, on a Go
//! corpus, the source of most dataflow noise: `fmt.Errorf("…%v", n)` makes
//! `n` taint an error that is returned nine hops later; `assert.Equal(t,
//! a, b)` makes `a` "write" `b`. A summary replaces the default with the
//! function's actual shape: which inputs reach the result, which are
//! written and from what, and whether the result (or a filled buffer) is
//! external data — a read, a fetch — that nothing in the call produced.
//!
//! Three lookups, in order: a **qualified** name (`fmt.Sprintf`,
//! `os.path.join`, `JSON.parse`) when the receiver is a dotted name the
//! table knows as a package or type; a **method** by name on any other
//! receiver (`s.strip()`, `buf.WriteString(x)`, `list.append(x)`), typed
//! by nothing but its name, so a shape must hold for every type that
//! commonly has the method; a **bare** name (`strcpy`, `append`, `len`).
//! A name the table does not know keeps the default. Every shape here is
//! meant to be the truth for the library in question; a shape that is
//! *tighter* than the truth would drop a real flow, so when types could
//! disagree ("does `add` return the receiver?") the shape says the union.

/// What a summarised call does with its inputs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shape {
    /// Every argument reaches the result: a formatter, a joiner, a
    /// converter, a parser of its input.
    Args,
    /// The receiver and every argument reach the result.
    RecvArgs,
    /// Only the receiver reaches the result: an accessor, a transform.
    Recv,
    /// Nothing reaches the result: a boolean, a count, a fresh handle.
    Nothing,
    /// The result is external data — a read, a fetch, an environment
    /// lookup — that nothing in the call produced.
    External,
    /// The receiver is written from the arguments and is the result (a
    /// builder's `append`, a list's `push`, a writer's `Write`).
    Mutates,
    /// Argument 0 is written from the rest and is the result (`strcpy`,
    /// `strcat`, `memcpy`, `sprintf`).
    WritesFirst,
    /// Argument 1 is written from argument 0 (`json.Unmarshal(data, &v)`).
    WritesSecondFromFirst,
    /// Argument 0 is filled with external data and is the result
    /// (`fgets(buf, n, f)`).
    FillsFirst,
    /// Argument 1 is filled with external data; the result is a count
    /// (`read(fd, buf, n)`, `recv`).
    FillsSecond,
    /// Everything after argument 0 is filled with external data
    /// (`scanf(fmt, &a, &b)`).
    FillsRest,
    /// Argument 0 is written from the receiver (`dec.Decode(&v)`,
    /// `c.ShouldBind(&form)`); the result is an error, nothing.
    WritesFirstFromRecv,
    /// Every argument is written from the receiver (`rows.Scan(&a, &b)`).
    WritesRestFromRecv,
}

/// An input of a call.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Slot {
    Recv,
    Arg(u8),
    /// Every positional argument from this index on.
    Rest(u8),
    /// External data: the call's own contribution.
    Ext,
}

/// A shape, spelled out.
#[derive(Debug, Clone, Copy)]
pub struct Summary {
    pub result: &'static [Slot],
    /// `(what is written, from what)`.
    pub writes: &'static [(Slot, &'static [Slot])],
}

impl Summary {
    pub fn of(shape: Shape) -> Summary {
        use Slot::*;
        match shape {
            Shape::Args => Summary { result: &[Rest(0)], writes: &[] },
            Shape::RecvArgs => Summary { result: &[Recv, Rest(0)], writes: &[] },
            Shape::Recv => Summary { result: &[Recv], writes: &[] },
            Shape::Nothing => Summary { result: &[], writes: &[] },
            Shape::External => Summary { result: &[Ext], writes: &[] },
            Shape::Mutates => Summary { result: &[Recv], writes: &[(Recv, &[Rest(0)])] },
            Shape::WritesFirst => Summary { result: &[Arg(0)], writes: &[(Arg(0), &[Rest(1)])] },
            Shape::WritesSecondFromFirst => Summary { result: &[], writes: &[(Arg(1), &[Arg(0)])] },
            Shape::FillsFirst => Summary { result: &[Arg(0)], writes: &[(Arg(0), &[Ext])] },
            Shape::FillsSecond => Summary { result: &[], writes: &[(Arg(1), &[Ext])] },
            Shape::FillsRest => Summary { result: &[], writes: &[(Rest(1), &[Ext])] },
            Shape::WritesFirstFromRecv => Summary { result: &[], writes: &[(Arg(0), &[Recv])] },
            Shape::WritesRestFromRecv => Summary { result: &[], writes: &[(Rest(0), &[Recv])] },
        }
    }

    /// Does external data enter anywhere?
    pub fn external(&self) -> bool {
        self.result.contains(&Slot::Ext) || self.writes.iter().any(|(_, from)| from.contains(&Slot::Ext))
    }
}

// Language groups: a summary tagged `js` applies to javascript, typescript
// and tsx; `c` to c and cpp; `*` to every language.
fn lang_matches(tag: &str, lang: &str) -> bool {
    tag.split(',').any(|t| {
        t == "*"
            || t == lang
            || (t == "js" && matches!(lang, "javascript" | "typescript" | "tsx"))
            || (t == "c" && matches!(lang, "c" | "cpp"))
    })
}

use Shape::*;

/// `(languages, qualifier, name, shape)`.
static QUALIFIED: &[(&str, &str, &str, Shape)] = &[
    // --- Go ---
    ("go", "fmt", "Sprintf", Args),
    ("go", "fmt", "Sprint", Args),
    ("go", "fmt", "Sprintln", Args),
    ("go", "fmt", "Errorf", Args),
    ("go", "fmt", "Println", Nothing),
    ("go", "fmt", "Printf", Nothing),
    ("go", "fmt", "Print", Nothing),
    ("go", "fmt", "Fprintf", WritesFirst),
    ("go", "fmt", "Fprintln", WritesFirst),
    ("go", "fmt", "Fprint", WritesFirst),
    ("go", "fmt", "Sscanf", FillsRest),
    ("go", "fmt", "Sscan", FillsRest),
    ("go", "errors", "New", Args),
    ("go", "errors", "Wrap", Args),
    ("go", "errors", "Wrapf", Args),
    ("go", "errors", "Is", Nothing),
    ("go", "errors", "As", Nothing),
    ("go", "errors", "Unwrap", Args),
    ("go", "strings", "ToUpper", Args),
    ("go", "strings", "ToLower", Args),
    ("go", "strings", "TrimSpace", Args),
    ("go", "strings", "Trim", Args),
    ("go", "strings", "TrimPrefix", Args),
    ("go", "strings", "TrimSuffix", Args),
    ("go", "strings", "TrimLeft", Args),
    ("go", "strings", "TrimRight", Args),
    ("go", "strings", "Split", Args),
    ("go", "strings", "SplitN", Args),
    ("go", "strings", "Fields", Args),
    ("go", "strings", "Join", Args),
    ("go", "strings", "Replace", Args),
    ("go", "strings", "ReplaceAll", Args),
    ("go", "strings", "Repeat", Args),
    ("go", "strings", "Title", Args),
    ("go", "strings", "Cut", Args),
    ("go", "strings", "NewReader", Args),
    ("go", "strings", "NewReplacer", Args),
    ("go", "strings", "Contains", Nothing),
    ("go", "strings", "HasPrefix", Nothing),
    ("go", "strings", "HasSuffix", Nothing),
    ("go", "strings", "EqualFold", Nothing),
    ("go", "strings", "Index", Nothing),
    ("go", "strings", "LastIndex", Nothing),
    ("go", "strings", "Count", Nothing),
    ("go", "strconv", "Itoa", Args),
    ("go", "strconv", "Quote", Args),
    ("go", "strconv", "FormatInt", Args),
    ("go", "strconv", "FormatBool", Nothing),
    ("go", "strconv", "Atoi", Nothing),
    ("go", "strconv", "ParseInt", Nothing),
    ("go", "strconv", "ParseBool", Nothing),
    ("go", "strconv", "ParseFloat", Nothing),
    ("go", "strconv", "Unquote", Args),
    ("go", "path", "Join", Args),
    ("go", "path", "Clean", Args),
    ("go", "path", "Base", Args),
    ("go", "path", "Dir", Args),
    ("go", "path", "Ext", Args),
    ("go", "path", "IsAbs", Nothing),
    ("go", "filepath", "Join", Args),
    ("go", "filepath", "Clean", Args),
    ("go", "filepath", "Base", Args),
    ("go", "filepath", "Dir", Args),
    ("go", "filepath", "Ext", Args),
    ("go", "filepath", "Abs", Args),
    ("go", "filepath", "Rel", Args),
    ("go", "filepath", "ToSlash", Args),
    ("go", "filepath", "FromSlash", Args),
    ("go", "filepath", "IsAbs", Nothing),
    ("go", "json", "Marshal", Args),
    ("go", "json", "MarshalIndent", Args),
    ("go", "json", "Unmarshal", WritesSecondFromFirst),
    ("go", "json", "NewDecoder", Args),
    ("go", "json", "NewEncoder", Args),
    ("go", "xml", "Marshal", Args),
    ("go", "xml", "Unmarshal", WritesSecondFromFirst),
    ("go", "yaml", "Marshal", Args),
    ("go", "yaml", "Unmarshal", WritesSecondFromFirst),
    ("go", "io", "ReadAll", Args),
    ("go", "io", "Copy", WritesFirst),
    ("go", "io", "WriteString", WritesFirst),
    ("go", "io", "NopCloser", Args),
    ("go", "ioutil", "ReadAll", Args),
    ("go", "ioutil", "ReadFile", External),
    ("go", "os", "ReadFile", External),
    ("go", "os", "Getenv", External),
    ("go", "os", "LookupEnv", External),
    ("go", "os", "Open", Nothing),
    ("go", "os", "Create", Nothing),
    ("go", "os", "Stat", Nothing),
    ("go", "os", "Getwd", External),
    ("go", "bytes", "NewBuffer", Args),
    ("go", "bytes", "NewBufferString", Args),
    ("go", "bytes", "NewReader", Args),
    ("go", "bytes", "TrimSpace", Args),
    ("go", "bytes", "ToLower", Args),
    ("go", "bytes", "ToUpper", Args),
    ("go", "bytes", "Contains", Nothing),
    ("go", "bytes", "Equal", Nothing),
    ("go", "bytes", "HasPrefix", Nothing),
    ("go", "bufio", "NewReader", Args),
    ("go", "bufio", "NewScanner", Args),
    ("go", "bufio", "NewWriter", Args),
    ("go", "url", "QueryEscape", Args),
    ("go", "url", "PathEscape", Args),
    ("go", "url", "QueryUnescape", Args),
    ("go", "url", "PathUnescape", Args),
    ("go", "url", "Parse", Args),
    ("go", "html", "EscapeString", Args),
    ("go", "html", "UnescapeString", Args),
    ("go", "template", "HTMLEscapeString", Args),
    ("go", "hex", "EncodeToString", Args),
    ("go", "hex", "DecodeString", Args),
    ("go", "time", "Now", External),
    ("go", "time", "Since", Nothing),
    ("go", "time", "Duration", Args),
    ("go", "sort", "Slice", Nothing),
    ("go", "sort", "Strings", Nothing),
    ("go", "sort", "Ints", Nothing),
    ("go", "sort", "Sort", Nothing),
    ("go", "context", "Background", Nothing),
    ("go", "context", "TODO", Nothing),
    ("go", "context", "WithCancel", Args),
    ("go", "context", "WithTimeout", Args),
    ("go", "context", "WithValue", Args),
    ("go", "log", "Printf", Nothing),
    ("go", "log", "Println", Nothing),
    ("go", "log", "Fatal", Nothing),
    ("go", "log", "Fatalf", Nothing),
    ("go", "log", "Error", Nothing),
    ("go", "log", "Warn", Nothing),
    ("go", "log", "Info", Nothing),
    ("go", "log", "Debug", Nothing),
    ("go", "log", "Trace", Nothing),
    ("go", "assert", "Equal", Nothing),
    ("go", "assert", "NotEqual", Nothing),
    ("go", "assert", "NoError", Nothing),
    ("go", "assert", "Error", Nothing),
    ("go", "assert", "True", Nothing),
    ("go", "assert", "False", Nothing),
    ("go", "assert", "Nil", Nothing),
    ("go", "assert", "NotNil", Nothing),
    ("go", "assert", "Len", Nothing),
    ("go", "assert", "Empty", Nothing),
    ("go", "assert", "NotEmpty", Nothing),
    ("go", "assert", "Contains", Nothing),
    ("go", "assert", "EqualValues", Nothing),
    ("go", "assert", "ErrorIs", Nothing),
    ("go", "assert", "Greater", Nothing),
    ("go", "assert", "Less", Nothing),
    ("go", "assert", "Fail", Nothing),
    ("go", "require", "Equal", Nothing),
    ("go", "require", "NotEqual", Nothing),
    ("go", "require", "NoError", Nothing),
    ("go", "require", "Error", Nothing),
    ("go", "require", "True", Nothing),
    ("go", "require", "False", Nothing),
    ("go", "require", "Nil", Nothing),
    ("go", "require", "NotNil", Nothing),
    ("go", "require", "Len", Nothing),
    ("go", "require", "Empty", Nothing),
    ("go", "require", "NotEmpty", Nothing),
    ("go", "require", "Contains", Nothing),
    ("go", "require", "EqualValues", Nothing),
    ("go", "require", "ErrorIs", Nothing),
    ("go", "require", "Greater", Nothing),
    ("go", "require", "Less", Nothing),
    ("go", "require", "Fail", Nothing),
    ("go", "http", "NewRequest", Args),
    ("go", "http", "NewRequestWithContext", Args),
    ("go", "http", "Get", External),
    ("go", "http", "Post", External),
    ("go", "http", "Error", Nothing),
    ("go", "http", "Redirect", Nothing),
    ("go", "http", "StatusText", Nothing),
    ("go", "sql", "Open", Nothing),
    ("go", "sql", "Named", Args),
    ("go", "template", "New", Nothing),
    ("go", "template", "Must", Args),
    ("go", "exec", "Command", Args),
    ("go", "exec", "CommandContext", Args),
    ("go", "exec", "LookPath", Args),
    ("go", "regexp", "MustCompile", Args),
    ("go", "regexp", "Compile", Args),
    ("go", "regexp", "MatchString", Nothing),
    ("go", "regexp", "QuoteMeta", Args),
    ("go", "utf8", "RuneCountInString", Nothing),
    ("go", "utf8", "ValidString", Nothing),
    ("go", "unicode", "IsLetter", Nothing),
    ("go", "unicode", "IsDigit", Nothing),
    ("go", "unicode", "IsSpace", Nothing),
    ("go", "rand", "Intn", Nothing),
    ("go", "rand", "Int", Nothing),
    ("go", "rand", "Read", FillsFirst),
    ("go", "binary", "Read", FillsRest),
    ("go", "binary", "Write", Nothing),
    ("go", "sha256", "Sum256", Args),
    ("go", "sha1", "Sum", Args),
    ("go", "md5", "Sum", Args),
    ("go", "hmac", "New", Nothing),
    ("go", "hmac", "Equal", Nothing),
    ("go", "bcrypt", "GenerateFromPassword", Args),
    ("go", "bcrypt", "CompareHashAndPassword", Nothing),
    ("go", "atomic", "AddInt64", Nothing),
    ("go", "atomic", "LoadInt64", Nothing),
    ("go", "atomic", "StoreInt64", Nothing),
    ("go", "reflect", "TypeOf", Nothing),
    ("go", "reflect", "ValueOf", Args),
    ("go", "reflect", "DeepEqual", Nothing),
    ("go", "mime", "TypeByExtension", Nothing),
    ("go", "user", "Current", External),
    ("go", "net", "JoinHostPort", Args),
    ("go", "net", "SplitHostPort", Args),
    ("go", "net", "ParseIP", Args),
    ("go", "net", "Dial", Nothing),
    ("go", "gzip", "NewReader", Args),
    ("go", "gzip", "NewWriter", Args),
    ("go", "tar", "NewReader", Args),
    ("go", "zip", "NewReader", Args),
    ("go", "csv", "NewReader", Args),
    ("go", "csv", "NewWriter", Args),
    ("go", "uuid", "New", Nothing),
    ("go", "uuid", "NewString", Nothing),
    ("go", "uuid", "Parse", Args),
    // --- Python ---
    ("python", "os.path", "join", Args),
    ("python", "os.path", "basename", Args),
    ("python", "os.path", "dirname", Args),
    ("python", "os.path", "abspath", Args),
    ("python", "os.path", "normpath", Args),
    ("python", "os.path", "realpath", Args),
    ("python", "os.path", "expanduser", Args),
    ("python", "os.path", "splitext", Args),
    ("python", "os.path", "split", Args),
    ("python", "os.path", "relpath", Args),
    ("python", "os.path", "exists", Nothing),
    ("python", "os.path", "isfile", Nothing),
    ("python", "os.path", "isdir", Nothing),
    ("python", "os.path", "isabs", Nothing),
    ("python", "os.path", "getsize", Nothing),
    ("python", "os", "getenv", External),
    ("python", "os", "getcwd", External),
    ("python", "os", "listdir", External),
    ("python", "os", "fspath", Args),
    ("python", "os.environ", "get", External),
    ("python", "json", "loads", Args),
    ("python", "json", "dumps", Args),
    ("python", "json", "load", Args),
    ("python", "json", "dump", Nothing),
    ("python", "base64", "b64encode", Args),
    ("python", "base64", "b64decode", Args),
    ("python", "base64", "urlsafe_b64encode", Args),
    ("python", "base64", "urlsafe_b64decode", Args),
    ("python", "urllib.parse", "quote", Args),
    ("python", "urllib.parse", "quote_plus", Args),
    ("python", "urllib.parse", "unquote", Args),
    ("python", "urllib.parse", "unquote_plus", Args),
    ("python", "urllib.parse", "urlencode", Args),
    ("python", "urllib.parse", "urljoin", Args),
    ("python", "urllib.parse", "urlparse", Args),
    ("python", "urllib.parse", "urlsplit", Args),
    ("python", "urllib.parse", "parse_qs", Args),
    ("python", "html", "escape", Args),
    ("python", "html", "unescape", Args),
    ("python", "re", "sub", Args),
    ("python", "re", "subn", Args),
    ("python", "re", "match", Args),
    ("python", "re", "search", Args),
    ("python", "re", "fullmatch", Args),
    ("python", "re", "findall", Args),
    ("python", "re", "finditer", Args),
    ("python", "re", "split", Args),
    ("python", "re", "escape", Args),
    ("python", "re", "compile", Args),
    ("python", "shlex", "quote", Args),
    ("python", "shlex", "split", Args),
    ("python", "shlex", "join", Args),
    ("python", "copy", "copy", Args),
    ("python", "copy", "deepcopy", Args),
    ("python", "textwrap", "dedent", Args),
    ("python", "textwrap", "indent", Args),
    ("python", "random", "shuffle", Nothing),
    ("python", "random", "choice", Args),
    ("python", "random", "randint", Nothing),
    ("python", "random", "random", Nothing),
    ("python", "time", "time", Nothing),
    ("python", "time", "sleep", Nothing),
    ("python", "datetime", "now", Nothing),
    ("python", "datetime.datetime", "now", Nothing),
    ("python", "sys", "exit", Nothing),
    ("python", "logging", "info", Nothing),
    ("python", "logging", "debug", Nothing),
    ("python", "logging", "warning", Nothing),
    ("python", "logging", "error", Nothing),
    ("python", "logging", "exception", Nothing),
    ("python", "logger", "info", Nothing),
    ("python", "logger", "debug", Nothing),
    ("python", "logger", "warning", Nothing),
    ("python", "logger", "error", Nothing),
    ("python", "logger", "exception", Nothing),
    ("python", "hashlib", "sha256", Args),
    ("python", "hashlib", "md5", Args),
    ("python", "hashlib", "sha1", Args),
    ("python", "sys.stdin", "read", External),
    ("python", "sys.stdin", "readline", External),
    ("python", "subprocess", "run", External),
    ("python", "subprocess", "check_output", External),
    ("python", "subprocess", "Popen", Nothing),
    ("python", "subprocess", "call", Nothing),
    ("python", "os", "system", Nothing),
    ("python", "os", "popen", External),
    ("python", "os", "remove", Nothing),
    ("python", "os", "makedirs", Nothing),
    ("python", "os", "mkdir", Nothing),
    ("python", "os", "chdir", Nothing),
    ("python", "os", "walk", External),
    ("python", "os", "urandom", External),
    ("python", "shutil", "copy", Nothing),
    ("python", "shutil", "copyfile", Nothing),
    ("python", "shutil", "rmtree", Nothing),
    ("python", "shutil", "move", Nothing),
    ("python", "shutil", "which", Args),
    ("python", "requests", "get", External),
    ("python", "requests", "post", External),
    ("python", "requests", "put", External),
    ("python", "requests", "delete", External),
    ("python", "requests", "request", External),
    ("python", "urllib.request", "urlopen", External),
    ("python", "urllib.request", "Request", Args),
    ("python", "flask", "jsonify", Args),
    ("python", "flask", "render_template", Args),
    ("python", "flask", "render_template_string", Args),
    ("python", "flask", "redirect", Args),
    ("python", "flask", "abort", Nothing),
    ("python", "flask", "url_for", Args),
    ("python", "flask", "make_response", Args),
    ("python", "flask", "escape", Args),
    ("python", "markupsafe", "escape", Args),
    ("python", "markupsafe", "Markup", Args),
    ("python", "request", "get_json", External),
    ("python", "request.args", "get", External),
    ("python", "request.form", "get", External),
    ("python", "request.headers", "get", External),
    ("python", "request.cookies", "get", External),
    ("python", "request.files", "get", External),
    ("python", "django.shortcuts", "render", Args),
    ("python", "django.shortcuts", "redirect", Args),
    ("python", "django.shortcuts", "get_object_or_404", Args),
    ("python", "django.http", "HttpResponse", Args),
    ("python", "django.http", "JsonResponse", Args),
    ("python", "django.http", "HttpResponseRedirect", Args),
    ("python", "django.utils.html", "escape", Args),
    ("python", "django.utils.html", "format_html", Args),
    ("python", "django.utils.html", "mark_safe", Args),
    ("python", "sqlite3", "connect", Nothing),
    ("python", "psycopg2", "connect", Nothing),
    ("python", "pymysql", "connect", Nothing),
    ("python", "pickle", "loads", Args),
    ("python", "pickle", "dumps", Args),
    ("python", "pickle", "load", External),
    ("python", "yaml", "safe_load", Args),
    ("python", "yaml", "load", Args),
    ("python", "yaml", "dump", Args),
    ("python", "yaml", "safe_dump", Args),
    ("python", "struct", "pack", Args),
    ("python", "struct", "unpack", Args),
    ("python", "zlib", "compress", Args),
    ("python", "zlib", "decompress", Args),
    ("python", "gzip", "open", Nothing),
    ("python", "io", "StringIO", Args),
    ("python", "io", "BytesIO", Args),
    ("python", "tempfile", "mkdtemp", Nothing),
    ("python", "tempfile", "NamedTemporaryFile", Nothing),
    ("python", "secrets", "token_hex", Nothing),
    ("python", "secrets", "token_urlsafe", Nothing),
    ("python", "uuid", "uuid4", Nothing),
    ("python", "itertools", "chain", Args),
    ("python", "functools", "partial", Args),
    ("python", "functools", "reduce", Args),
    ("python", "operator", "itemgetter", Nothing),
    ("python", "math", "floor", Nothing),
    ("python", "math", "ceil", Nothing),
    ("python", "math", "sqrt", Nothing),
    ("python", "ast", "literal_eval", Args),
    ("python", "inspect", "signature", Nothing),
    // --- JavaScript / TypeScript ---
    ("js", "JSON", "parse", Args),
    ("js", "JSON", "stringify", Args),
    ("js", "Object", "assign", WritesFirst),
    ("js", "Object", "keys", Args),
    ("js", "Object", "values", Args),
    ("js", "Object", "entries", Args),
    ("js", "Object", "freeze", Args),
    ("js", "Object", "fromEntries", Args),
    ("js", "Object", "create", Args),
    ("js", "Array", "from", Args),
    ("js", "Array", "of", Args),
    ("js", "Array", "isArray", Nothing),
    ("js", "Number", "isInteger", Nothing),
    ("js", "Number", "isNaN", Nothing),
    ("js", "Number", "parseInt", Nothing),
    ("js", "Number", "parseFloat", Nothing),
    ("js", "Math", "max", Nothing),
    ("js", "Math", "min", Nothing),
    ("js", "Math", "floor", Nothing),
    ("js", "Math", "ceil", Nothing),
    ("js", "Math", "round", Nothing),
    ("js", "Math", "abs", Nothing),
    ("js", "Math", "random", Nothing),
    ("js", "Buffer", "from", Args),
    ("js", "Buffer", "concat", Args),
    ("js", "Buffer", "alloc", Nothing),
    ("js", "Promise", "resolve", Args),
    ("js", "Promise", "reject", Args),
    ("js", "Promise", "all", Args),
    ("js", "Promise", "allSettled", Args),
    ("js", "Promise", "race", Args),
    ("js", "path", "join", Args),
    ("js", "path", "resolve", Args),
    ("js", "path", "basename", Args),
    ("js", "path", "dirname", Args),
    ("js", "path", "normalize", Args),
    ("js", "path", "extname", Args),
    ("js", "path", "relative", Args),
    ("js", "path", "isAbsolute", Nothing),
    ("js", "console", "log", Nothing),
    ("js", "console", "error", Nothing),
    ("js", "console", "warn", Nothing),
    ("js", "console", "info", Nothing),
    ("js", "console", "debug", Nothing),
    ("js", "String", "fromCharCode", Args),
    ("js", "process", "cwd", External),
    ("js", "Date", "now", Nothing),
    ("js", "document", "getElementById", External),
    ("js", "document", "querySelector", External),
    ("js", "document", "querySelectorAll", External),
    ("js", "document", "createElement", Nothing),
    ("js", "localStorage", "getItem", External),
    ("js", "sessionStorage", "getItem", External),
    ("js", "window", "fetch", External),
    ("js", "fs", "readFileSync", External),
    ("js", "fs", "readFile", External),
    ("js", "fs", "writeFileSync", Nothing),
    ("js", "fs", "writeFile", Nothing),
    ("js", "fs", "existsSync", Nothing),
    ("js", "fs", "mkdirSync", Nothing),
    ("js", "fs", "readdirSync", External),
    ("js", "fs", "statSync", Nothing),
    ("js", "fs", "unlinkSync", Nothing),
    ("js", "fs", "createReadStream", Nothing),
    ("js", "fs", "createWriteStream", Nothing),
    ("js", "child_process", "exec", Nothing),
    ("js", "child_process", "execSync", External),
    ("js", "child_process", "spawn", Nothing),
    ("js", "child_process", "spawnSync", External),
    ("js", "child_process", "execFile", Nothing),
    ("js", "crypto", "randomBytes", External),
    ("js", "crypto", "randomUUID", Nothing),
    ("js", "crypto", "createHash", Nothing),
    ("js", "crypto", "createHmac", Nothing),
    ("js", "os", "homedir", External),
    ("js", "os", "tmpdir", External),
    ("js", "os", "platform", Nothing),
    ("js", "url", "parse", Args),
    ("js", "url", "format", Args),
    ("js", "querystring", "parse", Args),
    ("js", "querystring", "stringify", Args),
    ("js", "util", "format", Args),
    ("js", "util", "inspect", Args),
    ("js", "util", "promisify", Args),
    ("js", "axios", "get", External),
    ("js", "axios", "post", External),
    ("js", "axios", "request", External),
    ("js", "express", "Router", Nothing),
    ("js", "express", "static", Nothing),
    ("js", "express", "json", Nothing),
    ("js", "res", "json", Nothing),
    ("js", "res", "send", Nothing),
    ("js", "res", "render", Nothing),
    ("js", "res", "redirect", Nothing),
    ("js", "res", "status", Nothing),
    ("js", "res", "sendFile", Nothing),
    ("js", "res", "cookie", Nothing),
    ("js", "res", "end", Nothing),
    ("js", "req.query", "get", External),
    ("js", "req.params", "get", External),
    ("js", "req.headers", "get", External),
    ("js", "$", "ajax", External),
    ("js", "$", "get", External),
    ("js", "$", "post", External),
    ("js", "DOMPurify", "sanitize", Args),
    ("js", "validator", "escape", Args),
    ("js", "he", "encode", Args),
    ("js", "he", "decode", Args),
    ("js", "lodash", "get", Args),
    ("js", "_", "get", Args),
    ("js", "_", "map", Args),
    ("js", "_", "filter", Args),
    ("js", "_", "merge", WritesFirst),
    ("js", "_", "cloneDeep", Args),
    ("js", "_", "isEmpty", Nothing),
    ("js", "_", "isNil", Nothing),
    ("js", "_", "escape", Args),
    ("js", "yaml", "load", Args),
    ("js", "yaml", "dump", Args),
    ("js", "Number", "toString", Args),
    ("js", "Reflect", "get", Args),
    ("js", "Reflect", "has", Nothing),
    // --- Java ---
    ("java", "String", "format", Args),
    ("java", "String", "valueOf", Args),
    ("java", "String", "join", Args),
    ("java", "String", "copyValueOf", Args),
    ("java", "Integer", "parseInt", Nothing),
    ("java", "Integer", "valueOf", Nothing),
    ("java", "Integer", "toString", Args),
    ("java", "Long", "parseLong", Nothing),
    ("java", "Long", "valueOf", Nothing),
    ("java", "Double", "parseDouble", Nothing),
    ("java", "Boolean", "parseBoolean", Nothing),
    ("java", "Boolean", "valueOf", Nothing),
    ("java", "Objects", "requireNonNull", Args),
    ("java", "Objects", "equals", Nothing),
    ("java", "Objects", "hash", Nothing),
    ("java", "Objects", "isNull", Nothing),
    ("java", "Objects", "nonNull", Nothing),
    ("java", "Objects", "toString", Args),
    ("java", "Arrays", "asList", Args),
    ("java", "Arrays", "copyOf", Args),
    ("java", "Arrays", "stream", Args),
    ("java", "Arrays", "toString", Args),
    ("java", "Arrays", "sort", Nothing),
    ("java", "Arrays", "fill", WritesFirst),
    ("java", "List", "of", Args),
    ("java", "List", "copyOf", Args),
    ("java", "Set", "of", Args),
    ("java", "Map", "of", Args),
    ("java", "Map", "entry", Args),
    ("java", "Collections", "unmodifiableList", Args),
    ("java", "Collections", "unmodifiableMap", Args),
    ("java", "Collections", "unmodifiableSet", Args),
    ("java", "Collections", "singletonList", Args),
    ("java", "Collections", "emptyList", Nothing),
    ("java", "Collections", "emptyMap", Nothing),
    ("java", "Collections", "sort", Nothing),
    ("java", "Optional", "of", Args),
    ("java", "Optional", "ofNullable", Args),
    ("java", "Optional", "empty", Nothing),
    ("java", "Paths", "get", Args),
    ("java", "Path", "of", Args),
    ("java", "Files", "readString", External),
    ("java", "Files", "readAllLines", External),
    ("java", "Files", "readAllBytes", External),
    ("java", "Files", "exists", Nothing),
    ("java", "Files", "isDirectory", Nothing),
    ("java", "System", "getenv", External),
    ("java", "System", "getProperty", External),
    ("java", "System", "currentTimeMillis", Nothing),
    ("java", "System", "nanoTime", Nothing),
    ("java", "Math", "max", Nothing),
    ("java", "Math", "min", Nothing),
    ("java", "Math", "abs", Nothing),
    ("java", "Base64", "getDecoder", Nothing),
    ("java", "Base64", "getEncoder", Nothing),
    ("java", "Pattern", "compile", Args),
    ("java", "Pattern", "matches", Nothing),
    ("java", "Pattern", "quote", Args),
    ("java", "URLEncoder", "encode", Args),
    ("java", "URLDecoder", "decode", Args),
    ("java", "log", "info", Nothing),
    ("java", "log", "debug", Nothing),
    ("java", "log", "warn", Nothing),
    ("java", "log", "error", Nothing),
    ("java", "logger", "info", Nothing),
    ("java", "logger", "debug", Nothing),
    ("java", "logger", "warn", Nothing),
    ("java", "logger", "error", Nothing),
    ("java", "LOG", "info", Nothing),
    ("java", "LOG", "debug", Nothing),
    ("java", "LOG", "warn", Nothing),
    ("java", "LOG", "error", Nothing),
    ("java", "Files", "write", Nothing),
    ("java", "Files", "writeString", Nothing),
    ("java", "Files", "createDirectories", Nothing),
    ("java", "Files", "delete", Nothing),
    ("java", "Files", "copy", Nothing),
    ("java", "Files", "move", Nothing),
    ("java", "Files", "newBufferedReader", Nothing),
    ("java", "Files", "newInputStream", Nothing),
    ("java", "Files", "lines", External),
    ("java", "Files", "list", External),
    ("java", "Files", "walk", External),
    ("java", "Files", "size", Nothing),
    ("java", "Runtime", "getRuntime", Nothing),
    ("java", "Thread", "sleep", Nothing),
    ("java", "Thread", "currentThread", Nothing),
    ("java", "UUID", "randomUUID", Nothing),
    ("java", "UUID", "fromString", Args),
    ("java", "Character", "isDigit", Nothing),
    ("java", "Character", "isLetter", Nothing),
    ("java", "Character", "toUpperCase", Args),
    ("java", "Character", "toLowerCase", Args),
    ("java", "StringUtils", "isBlank", Nothing),
    ("java", "StringUtils", "isEmpty", Nothing),
    ("java", "StringUtils", "isNotBlank", Nothing),
    ("java", "StringUtils", "isNotEmpty", Nothing),
    ("java", "StringUtils", "trim", Args),
    ("java", "StringUtils", "join", Args),
    ("java", "StringUtils", "substring", Args),
    ("java", "StringUtils", "defaultString", Args),
    ("java", "StringUtils", "replace", Args),
    ("java", "StringEscapeUtils", "escapeHtml4", Args),
    ("java", "StringEscapeUtils", "escapeJava", Args),
    ("java", "StringEscapeUtils", "unescapeHtml4", Args),
    ("java", "HtmlUtils", "htmlEscape", Args),
    ("java", "Jsoup", "clean", Args),
    ("java", "Jsoup", "parse", Args),
    ("java", "ResponseEntity", "ok", Args),
    ("java", "ResponseEntity", "status", Nothing),
    ("java", "ResponseEntity", "badRequest", Nothing),
    ("java", "Stream", "of", Args),
    ("java", "Collectors", "toList", Nothing),
    ("java", "Collectors", "toSet", Nothing),
    ("java", "Collectors", "joining", Nothing),
    ("java", "Collectors", "toMap", Nothing),
    ("java", "IOUtils", "toString", Args),
    ("java", "IOUtils", "toByteArray", Args),
    ("java", "IOUtils", "copy", Nothing),
    ("java", "FileUtils", "readFileToString", External),
    ("java", "FileUtils", "writeStringToFile", Nothing),
    ("java", "DriverManager", "getConnection", Nothing),
    ("java", "LoggerFactory", "getLogger", Nothing),
    ("java", "Logger", "getLogger", Nothing),
    ("java", "System", "exit", Nothing),
    ("java", "System", "arraycopy", Nothing),
    ("java", "System", "lineSeparator", Nothing),
    ("java", "Executors", "newFixedThreadPool", Nothing),
    ("java", "CompletableFuture", "supplyAsync", Args),
    ("java", "CompletableFuture", "completedFuture", Args),
    // --- C# ---
    ("csharp", "String", "Format", Args),
    ("csharp", "string", "Format", Args),
    ("csharp", "String", "Join", Args),
    ("csharp", "string", "Join", Args),
    ("csharp", "String", "Concat", Args),
    ("csharp", "string", "Concat", Args),
    ("csharp", "String", "IsNullOrEmpty", Nothing),
    ("csharp", "string", "IsNullOrEmpty", Nothing),
    ("csharp", "String", "IsNullOrWhiteSpace", Nothing),
    ("csharp", "string", "IsNullOrWhiteSpace", Nothing),
    ("csharp", "Path", "Combine", Args),
    ("csharp", "Path", "GetFileName", Args),
    ("csharp", "Path", "GetDirectoryName", Args),
    ("csharp", "Path", "GetFullPath", Args),
    ("csharp", "Path", "GetExtension", Args),
    ("csharp", "Path", "Join", Args),
    ("csharp", "File", "ReadAllText", External),
    ("csharp", "File", "ReadAllLines", External),
    ("csharp", "File", "ReadAllBytes", External),
    ("csharp", "File", "Exists", Nothing),
    ("csharp", "Directory", "Exists", Nothing),
    ("csharp", "Environment", "GetEnvironmentVariable", External),
    ("csharp", "Console", "ReadLine", External),
    ("csharp", "Console", "WriteLine", Nothing),
    ("csharp", "Console", "Write", Nothing),
    ("csharp", "Int32", "Parse", Nothing),
    ("csharp", "int", "Parse", Nothing),
    ("csharp", "Int32", "TryParse", Nothing),
    ("csharp", "int", "TryParse", Nothing),
    ("csharp", "Convert", "ToInt32", Nothing),
    ("csharp", "Convert", "ToInt64", Nothing),
    ("csharp", "Convert", "ToBoolean", Nothing),
    ("csharp", "Convert", "ToString", Args),
    ("csharp", "Convert", "ToBase64String", Args),
    ("csharp", "Convert", "FromBase64String", Args),
    ("csharp", "Encoding.UTF8", "GetBytes", Args),
    ("csharp", "Encoding.UTF8", "GetString", Args),
    ("csharp", "JsonConvert", "SerializeObject", Args),
    ("csharp", "JsonConvert", "DeserializeObject", Args),
    ("csharp", "JsonSerializer", "Serialize", Args),
    ("csharp", "JsonSerializer", "Deserialize", Args),
    ("csharp", "HttpUtility", "UrlEncode", Args),
    ("csharp", "HttpUtility", "UrlDecode", Args),
    ("csharp", "HttpUtility", "HtmlEncode", Args),
    ("csharp", "HttpUtility", "HtmlDecode", Args),
    ("csharp", "Regex", "Replace", Args),
    ("csharp", "Regex", "Match", Args),
    ("csharp", "Regex", "IsMatch", Nothing),
    ("csharp", "Regex", "Escape", Args),
    ("csharp", "Math", "Max", Nothing),
    ("csharp", "Math", "Min", Nothing),
    ("csharp", "Math", "Abs", Nothing),
    ("csharp", "DateTime", "Now", Nothing),
    ("csharp", "Guid", "NewGuid", Nothing),
    // --- Rust ---
    ("rust", "String", "from", Args),
    ("rust", "String", "new", Nothing),
    ("rust", "String", "from_utf8", Args),
    ("rust", "String", "from_utf8_lossy", Args),
    ("rust", "Vec", "new", Nothing),
    ("rust", "Vec", "with_capacity", Nothing),
    ("rust", "Vec", "from", Args),
    ("rust", "PathBuf", "from", Args),
    ("rust", "Path", "new", Args),
    ("rust", "Box", "new", Args),
    ("rust", "Rc", "new", Args),
    ("rust", "Arc", "new", Args),
    ("rust", "Cow", "from", Args),
    ("rust", "std::env", "var", External),
    ("rust", "env", "var", External),
    ("rust", "env", "args", External),
    ("rust", "fs", "read_to_string", External),
    ("rust", "fs", "read", External),
    ("rust", "fs", "write", Nothing),
    ("rust", "std::fs", "read_to_string", External),
    ("rust", "std::fs", "read", External),
    ("rust", "serde_json", "to_string", Args),
    ("rust", "serde_json", "to_vec", Args),
    ("rust", "serde_json", "from_str", Args),
    ("rust", "serde_json", "from_slice", Args),
    ("rust", "serde_json", "json", Args),
    ("rust", "Instant", "now", Nothing),
    ("rust", "SystemTime", "now", Nothing),
    // --- Ruby ---
    ("ruby", "File", "join", Args),
    ("ruby", "File", "basename", Args),
    ("ruby", "File", "dirname", Args),
    ("ruby", "File", "expand_path", Args),
    ("ruby", "File", "extname", Args),
    ("ruby", "File", "read", External),
    ("ruby", "File", "readlines", External),
    ("ruby", "File", "exist?", Nothing),
    ("ruby", "File", "file?", Nothing),
    ("ruby", "File", "directory?", Nothing),
    ("ruby", "JSON", "parse", Args),
    ("ruby", "JSON", "generate", Args),
    ("ruby", "JSON", "dump", Args),
    ("ruby", "YAML", "load", Args),
    ("ruby", "YAML", "dump", Args),
    ("ruby", "CGI", "escape", Args),
    ("ruby", "CGI", "unescape", Args),
    ("ruby", "CGI", "escapeHTML", Args),
    ("ruby", "ERB::Util", "html_escape", Args),
    ("ruby", "URI", "encode_www_form", Args),
    ("ruby", "URI", "decode_www_form", Args),
    ("ruby", "URI", "join", Args),
    ("ruby", "URI", "parse", Args),
    ("ruby", "URI", "escape", Args),
    ("ruby", "Shellwords", "escape", Args),
    ("ruby", "Shellwords", "join", Args),
    ("ruby", "Shellwords", "split", Args),
    ("ruby", "Base64", "encode64", Args),
    ("ruby", "Base64", "decode64", Args),
    ("ruby", "Base64", "strict_encode64", Args),
    ("ruby", "Base64", "strict_decode64", Args),
    ("ruby", "Digest::SHA256", "hexdigest", Args),
    ("ruby", "Digest::MD5", "hexdigest", Args),
    ("ruby", "ENV", "fetch", External),
    ("ruby", "Time", "now", Nothing),
    ("ruby", "Rails.logger", "info", Nothing),
    ("ruby", "Rails.logger", "debug", Nothing),
    ("ruby", "Rails.logger", "warn", Nothing),
    ("ruby", "Rails.logger", "error", Nothing),
    ("ruby", "logger", "info", Nothing),
    ("ruby", "logger", "debug", Nothing),
    ("ruby", "logger", "warn", Nothing),
    ("ruby", "logger", "error", Nothing),
];

/// `(languages, name, shape)` — a bare call, no receiver.
static BARE: &[(&str, &str, Shape)] = &[
    // --- C / C++ ---
    ("c", "strcpy", WritesFirst),
    ("c", "strncpy", WritesFirst),
    ("c", "strcat", WritesFirst),
    ("c", "strncat", WritesFirst),
    ("c", "strlcpy", WritesFirst),
    ("c", "strlcat", WritesFirst),
    ("c", "memcpy", WritesFirst),
    ("c", "memmove", WritesFirst),
    ("c", "memset", WritesFirst),
    ("c", "sprintf", WritesFirst),
    ("c", "snprintf", WritesFirst),
    ("c", "vsprintf", WritesFirst),
    ("c", "vsnprintf", WritesFirst),
    ("c", "wcscpy", WritesFirst),
    ("c", "wcscat", WritesFirst),
    ("c", "strdup", Args),
    ("c", "strndup", Args),
    ("c", "strchr", Args),
    ("c", "strrchr", Args),
    ("c", "strstr", Args),
    ("c", "strtok", Args),
    ("c", "strtok_r", Args),
    ("c", "strlen", Nothing),
    ("c", "strcmp", Nothing),
    ("c", "strncmp", Nothing),
    ("c", "strcasecmp", Nothing),
    ("c", "memcmp", Nothing),
    ("c", "atoi", Nothing),
    ("c", "atol", Nothing),
    ("c", "atof", Nothing),
    ("c", "strtol", Nothing),
    ("c", "strtoul", Nothing),
    ("c", "strtod", Nothing),
    ("c", "isdigit", Nothing),
    ("c", "isalpha", Nothing),
    ("c", "isspace", Nothing),
    ("c", "toupper", Args),
    ("c", "tolower", Args),
    ("c", "malloc", Nothing),
    ("c", "calloc", Nothing),
    ("c", "realloc", Args),
    ("c", "free", Nothing),
    ("c", "sizeof", Nothing),
    ("c", "printf", Nothing),
    ("c", "fprintf", Nothing),
    ("c", "puts", Nothing),
    ("c", "fputs", Nothing),
    ("c", "putchar", Nothing),
    ("c", "perror", Nothing),
    ("c", "fgets", FillsFirst),
    ("c", "gets", FillsFirst),
    ("c", "gets_s", FillsFirst),
    ("c", "fgetc", External),
    ("c", "getc", External),
    ("c", "getchar", External),
    ("c", "getline", FillsFirst),
    ("c", "getenv", External),
    ("c", "read", FillsSecond),
    ("c", "pread", FillsSecond),
    ("c", "recv", FillsSecond),
    ("c", "recvfrom", FillsSecond),
    ("c", "fread", FillsFirst),
    ("c", "scanf", FillsRest),
    ("c", "fscanf", FillsRest),
    ("c", "sscanf", FillsRest),
    ("c", "fopen", Nothing),
    ("c", "open", Nothing),
    ("c", "close", Nothing),
    ("c", "fclose", Nothing),
    ("c", "write", Nothing),
    ("c", "fwrite", Nothing),
    ("c", "send", Nothing),
    ("c", "assert", Nothing),
    // --- Go builtins ---
    ("go", "append", Args),
    ("go", "copy", WritesFirst),
    ("go", "len", Nothing),
    ("go", "cap", Nothing),
    ("go", "make", Nothing),
    ("go", "new", Nothing),
    ("go", "delete", Nothing),
    ("go", "panic", Nothing),
    ("go", "print", Nothing),
    ("go", "println", Nothing),
    ("go", "string", Args),
    ("go", "int", Nothing),
    ("go", "int64", Nothing),
    ("go", "int32", Nothing),
    ("go", "uint", Nothing),
    ("go", "float64", Nothing),
    ("go", "bool", Nothing),
    ("go", "byte", Nothing),
    ("go", "rune", Nothing),
    ("go", "error", Args),
    ("go", "min", Nothing),
    ("go", "max", Nothing),
    ("go", "close", Nothing),
    // --- Python builtins ---
    ("python", "str", Args),
    ("python", "repr", Args),
    ("python", "bytes", Args),
    ("python", "bytearray", Args),
    ("python", "list", Args),
    ("python", "tuple", Args),
    ("python", "set", Args),
    ("python", "frozenset", Args),
    ("python", "dict", Args),
    ("python", "sorted", Args),
    ("python", "reversed", Args),
    ("python", "enumerate", Args),
    ("python", "zip", Args),
    ("python", "map", Args),
    ("python", "filter", Args),
    ("python", "iter", Args),
    ("python", "next", Args),
    ("python", "getattr", Args),
    ("python", "vars", Args),
    ("python", "format", Args),
    ("python", "join", Args),
    ("python", "int", Nothing),
    ("python", "float", Nothing),
    ("python", "bool", Nothing),
    ("python", "len", Nothing),
    ("python", "abs", Nothing),
    ("python", "round", Nothing),
    ("python", "min", Nothing),
    ("python", "max", Nothing),
    ("python", "sum", Nothing),
    ("python", "isinstance", Nothing),
    ("python", "issubclass", Nothing),
    ("python", "hasattr", Nothing),
    ("python", "callable", Nothing),
    ("python", "id", Nothing),
    ("python", "hash", Nothing),
    ("python", "type", Nothing),
    ("python", "range", Nothing),
    ("python", "print", Nothing),
    ("python", "input", External),
    ("python", "open", Nothing),
    ("python", "super", Nothing),
    ("python", "object", Nothing),
    // --- JavaScript ---
    ("js", "String", Args),
    ("js", "Number", Nothing),
    ("js", "Boolean", Nothing),
    ("js", "parseInt", Nothing),
    ("js", "parseFloat", Nothing),
    ("js", "isNaN", Nothing),
    ("js", "isFinite", Nothing),
    ("js", "encodeURIComponent", Args),
    ("js", "decodeURIComponent", Args),
    ("js", "encodeURI", Args),
    ("js", "decodeURI", Args),
    ("js", "escape", Args),
    ("js", "unescape", Args),
    ("js", "require", Nothing),
    ("js", "setTimeout", Nothing),
    ("js", "setInterval", Nothing),
    ("js", "clearTimeout", Nothing),
    ("js", "fetch", External),
    ("js", "prompt", External),
    ("js", "alert", Nothing),
    ("js", "Symbol", Nothing),
    ("js", "Error", Args),
    ("js", "TypeError", Args),
    ("js", "RangeError", Args),
    // --- Rust macros are not calls; bare Rust names ---
    ("rust", "format", Args),
    ("rust", "vec", Args),
    ("rust", "println", Nothing),
    ("rust", "eprintln", Nothing),
    ("rust", "print", Nothing),
    ("rust", "dbg", Args),
    ("rust", "assert", Nothing),
    ("rust", "assert_eq", Nothing),
    ("rust", "assert_ne", Nothing),
    ("rust", "debug_assert", Nothing),
    ("rust", "panic", Nothing),
    ("rust", "todo", Nothing),
    ("rust", "unreachable", Nothing),
    ("rust", "drop", Nothing),
    ("rust", "Some", Args),
    ("rust", "Ok", Args),
    ("rust", "Err", Args),
    // --- Ruby ---
    ("ruby", "puts", Nothing),
    ("ruby", "print", Nothing),
    ("ruby", "p", Args),
    ("ruby", "pp", Args),
    ("ruby", "raise", Nothing),
    ("ruby", "require", Nothing),
    ("ruby", "require_relative", Nothing),
    ("ruby", "gets", External),
    ("ruby", "Integer", Nothing),
    ("ruby", "Float", Nothing),
    ("ruby", "String", Args),
    ("ruby", "Array", Args),
    ("ruby", "format", Args),
    ("ruby", "sprintf", Args),
    ("ruby", "lambda", Nothing),
    ("ruby", "proc", Nothing),
];

/// `(languages, name, shape)` — a method on a receiver of unknown type.
/// A shape here must be the union over every common type with the method:
/// `get` returns the receiver's contents on a map and the argument's on
/// nothing common, so `Recv` is right; `add` returns the receiver on a
/// builder and a boolean on a set, so `Mutates` (receiver written, result
/// the receiver) covers both.
static METHODS: &[(&str, &str, Shape)] = &[
    // Pure transforms: receiver (and arguments) reach the result.
    ("*", "strip", RecvArgs),
    ("*", "lstrip", RecvArgs),
    ("*", "rstrip", RecvArgs),
    ("*", "trim", Recv),
    ("*", "trimStart", Recv),
    ("*", "trimEnd", Recv),
    ("*", "Trim", RecvArgs),
    ("*", "TrimStart", RecvArgs),
    ("*", "TrimEnd", RecvArgs),
    ("*", "TrimSpace", Recv),
    ("*", "TrimPrefix", RecvArgs),
    ("*", "TrimSuffix", RecvArgs),
    ("*", "trim_start", Recv),
    ("*", "trim_end", Recv),
    ("*", "trim_matches", RecvArgs),
    ("*", "lower", Recv),
    ("*", "upper", Recv),
    ("*", "title", Recv),
    ("*", "capitalize", Recv),
    ("*", "casefold", Recv),
    ("*", "swapcase", Recv),
    ("*", "toLowerCase", Recv),
    ("*", "toUpperCase", Recv),
    ("*", "toLocaleLowerCase", Recv),
    ("*", "toLocaleUpperCase", Recv),
    ("*", "ToLower", Recv),
    ("*", "ToUpper", Recv),
    ("*", "ToLowerInvariant", Recv),
    ("*", "ToUpperInvariant", Recv),
    ("*", "to_lowercase", Recv),
    ("*", "to_uppercase", Recv),
    ("*", "downcase", Recv),
    ("*", "upcase", Recv),
    ("*", "chomp", Recv),
    ("*", "chop", Recv),
    ("*", "squish", Recv),
    ("*", "split", RecvArgs),
    ("*", "rsplit", RecvArgs),
    ("*", "splitlines", Recv),
    ("*", "Split", RecvArgs),
    ("*", "partition", RecvArgs),
    ("*", "rpartition", RecvArgs),
    ("*", "join", RecvArgs),
    ("*", "Join", RecvArgs),
    ("*", "replace", RecvArgs),
    ("*", "replaceAll", RecvArgs),
    ("*", "Replace", RecvArgs),
    ("*", "ReplaceAll", RecvArgs),
    ("*", "sub", RecvArgs),
    ("*", "gsub", RecvArgs),
    ("*", "format", RecvArgs),
    ("*", "Format", RecvArgs),
    ("*", "format_map", RecvArgs),
    ("*", "concat", RecvArgs),
    ("*", "Concat", RecvArgs),
    ("*", "substring", Recv),
    ("*", "Substring", Recv),
    ("*", "substr", Recv),
    ("*", "slice", Recv),
    ("*", "Slice", Recv),
    ("*", "splice", Recv),
    ("*", "at", Recv),
    ("*", "charAt", Recv),
    ("*", "chars", Recv),
    ("*", "bytes", Recv),
    ("*", "Bytes", Recv),
    ("*", "String", Recv),
    ("*", "toString", Recv),
    ("*", "ToString", Recv),
    ("*", "to_s", Recv),
    ("*", "to_str", Recv),
    ("*", "to_string", Recv),
    ("*", "to_owned", Recv),
    ("*", "to_vec", Recv),
    ("*", "to_a", Recv),
    ("*", "to_sym", Recv),
    ("*", "to_json", Recv),
    ("*", "toJSON", Recv),
    ("*", "as_str", Recv),
    ("*", "as_bytes", Recv),
    ("*", "as_ref", Recv),
    ("*", "as_deref", Recv),
    ("*", "as_slice", Recv),
    ("*", "borrow", Recv),
    ("*", "clone", Recv),
    ("*", "cloned", Recv),
    ("*", "copied", Recv),
    ("*", "copy", Recv),
    ("*", "dup", Recv),
    ("*", "unwrap", Recv),
    ("*", "unwrap_or", RecvArgs),
    ("*", "unwrap_or_else", RecvArgs),
    ("*", "unwrap_or_default", Recv),
    ("*", "expect", Recv),
    ("*", "ok_or", RecvArgs),
    ("*", "ok_or_else", RecvArgs),
    ("*", "map_err", RecvArgs),
    ("*", "and_then", RecvArgs),
    ("*", "or_else", RecvArgs),
    ("*", "then", RecvArgs),
    ("*", "catch", RecvArgs),
    ("*", "finally", Recv),
    ("*", "orElse", RecvArgs),
    ("*", "orElseGet", RecvArgs),
    ("*", "orElseThrow", Recv),
    ("*", "getOrDefault", RecvArgs),
    ("*", "encode", Recv),
    ("*", "decode", Recv),
    ("*", "Encode", Recv),
    ("*", "Decode", WritesFirstFromRecv),
    ("*", "Scan", WritesRestFromRecv),
    ("*", "Bind", WritesFirstFromRecv),
    ("*", "BindJSON", WritesFirstFromRecv),
    ("*", "ShouldBind", WritesFirstFromRecv),
    ("*", "ShouldBindJSON", WritesFirstFromRecv),
    ("*", "ShouldBindQuery", WritesFirstFromRecv),
    ("*", "ShouldBindUri", WritesFirstFromRecv),
    ("*", "UnmarshalJSON", Mutates),
    ("*", "UnmarshalText", Mutates),
    ("*", "EncodeToString", RecvArgs),
    ("*", "DecodeString", RecvArgs),
    ("*", "getBytes", Recv),
    ("*", "GetBytes", RecvArgs),
    ("*", "GetString", RecvArgs),
    ("*", "toCharArray", Recv),
    ("*", "intern", Recv),
    ("*", "normalize", Recv),
    ("*", "padStart", RecvArgs),
    ("*", "padEnd", RecvArgs),
    ("*", "PadLeft", RecvArgs),
    ("*", "PadRight", RecvArgs),
    ("*", "ljust", RecvArgs),
    ("*", "rjust", RecvArgs),
    ("*", "center", RecvArgs),
    ("*", "zfill", Recv),
    ("*", "repeat", Recv),
    ("*", "Repeat", Recv),
    ("*", "reverse", Recv),
    ("*", "reversed", Recv),
    ("*", "sort", Recv),
    ("*", "sorted", Recv),
    ("*", "sort_by", Recv),
    ("*", "sort_by_key", Recv),
    ("*", "uniq", Recv),
    ("*", "flatten", Recv),
    ("*", "flat", Recv),
    ("*", "flatMap", RecvArgs),
    ("*", "flat_map", RecvArgs),
    ("*", "compact", Recv),
    ("*", "map", RecvArgs),
    ("*", "Map", RecvArgs),
    ("*", "select", RecvArgs),
    ("*", "filter", RecvArgs),
    ("*", "filter_map", RecvArgs),
    ("*", "reject", RecvArgs),
    ("*", "reduce", RecvArgs),
    ("*", "fold", RecvArgs),
    ("*", "inject", RecvArgs),
    ("*", "collect", Recv),
    ("*", "iter", Recv),
    ("*", "iter_mut", Recv),
    ("*", "into_iter", Recv),
    ("*", "stream", Recv),
    ("*", "toArray", Recv),
    ("*", "toList", Recv),
    ("*", "entries", Recv),
    ("*", "keys", Recv),
    ("*", "values", Recv),
    ("*", "items", Recv),
    ("*", "keySet", Recv),
    ("*", "entrySet", Recv),
    ("*", "first", Recv),
    ("*", "last", Recv),
    ("*", "take", Recv),
    ("*", "skip", Recv),
    ("*", "drop", Recv),
    ("*", "peek", Recv),
    ("*", "next", Recv),
    ("*", "Next", Recv),
    ("*", "get", RecvArgs),
    ("*", "Get", RecvArgs),
    ("*", "getOrElse", RecvArgs),
    ("*", "fetch", RecvArgs),
    ("*", "dig", RecvArgs),
    ("*", "find", Recv),
    ("*", "Find", Recv),
    ("*", "detect", Recv),
    ("*", "pop", RecvArgs),
    ("*", "Pop", Recv),
    ("*", "shift", Recv),
    ("*", "remove", Recv),
    ("*", "Remove", Recv),
    ("*", "poll", Recv),
    ("*", "getValue", Recv),
    ("*", "getKey", Recv),
    ("*", "getName", Recv),
    ("*", "getPath", Recv),
    ("*", "getText", Recv),
    ("*", "getMessage", Recv),
    ("*", "getParameter", Recv),
    ("*", "getHeader", Recv),
    ("*", "getAttribute", Recv),
    ("*", "getProperty", Recv),
    ("*", "getInputStream", Recv),
    ("*", "getReader", Recv),
    ("*", "getBody", Recv),
    ("*", "getQueryString", Recv),
    ("*", "getRequestURI", Recv),
    ("*", "getContent", Recv),
    ("*", "Value", Recv),
    ("*", "Text", Recv),
    ("*", "Err", Recv),
    ("*", "Error", Recv),
    ("*", "Unwrap", Recv),
    ("*", "Query", RecvArgs),
    ("*", "Param", RecvArgs),
    ("*", "PathParam", RecvArgs),
    ("*", "FormValue", RecvArgs),
    ("*", "FormString", RecvArgs),
    ("*", "PostFormValue", RecvArgs),
    ("*", "Header", Recv),
    ("*", "Cookie", RecvArgs),
    ("*", "Read", FillsFirst),
    ("*", "ReadString", Recv),
    ("*", "ReadLine", Recv),
    ("*", "ReadBytes", Recv),
    ("*", "ReadAll", Recv),
    ("*", "ReadFrom", Mutates),
    ("*", "read", Recv),
    ("*", "readline", Recv),
    ("*", "readlines", Recv),
    ("*", "readLine", Recv),
    ("*", "text", Recv),
    ("*", "json", Recv),
    ("*", "body", Recv),
    ("*", "data", Recv),
    ("*", "result", Recv),
    ("*", "value", Recv),
    ("*", "unwrap_err", Recv),
    ("*", "path", Recv),
    ("*", "name", Recv),
    ("*", "len", Nothing),
    ("*", "Len", Nothing),
    ("*", "length", Nothing),
    ("*", "size", Nothing),
    ("*", "count", Nothing),
    ("*", "Count", Nothing),
    ("*", "is_empty", Nothing),
    ("*", "isEmpty", Nothing),
    ("*", "empty?", Nothing),
    ("*", "nil?", Nothing),
    ("*", "any?", Nothing),
    ("*", "none?", Nothing),
    ("*", "present?", Nothing),
    ("*", "blank?", Nothing),
    ("*", "is_some", Nothing),
    ("*", "is_none", Nothing),
    ("*", "is_ok", Nothing),
    ("*", "is_err", Nothing),
    ("*", "isPresent", Nothing),
    ("*", "isDigit", Nothing),
    ("*", "isdigit", Nothing),
    ("*", "isalpha", Nothing),
    ("*", "isalnum", Nothing),
    ("*", "isspace", Nothing),
    ("*", "isnumeric", Nothing),
    ("*", "contains", Nothing),
    ("*", "Contains", Nothing),
    ("*", "containsKey", Nothing),
    ("*", "includes", Nothing),
    ("*", "include?", Nothing),
    ("*", "has", Nothing),
    ("*", "Has", Nothing),
    ("*", "hasOwnProperty", Nothing),
    ("*", "has_key", Nothing),
    ("*", "has_key?", Nothing),
    ("*", "key?", Nothing),
    ("*", "startsWith", Nothing),
    ("*", "endsWith", Nothing),
    ("*", "StartsWith", Nothing),
    ("*", "EndsWith", Nothing),
    ("*", "starts_with", Nothing),
    ("*", "ends_with", Nothing),
    ("*", "start_with?", Nothing),
    ("*", "end_with?", Nothing),
    ("*", "startswith", Nothing),
    ("*", "endswith", Nothing),
    ("*", "HasPrefix", Nothing),
    ("*", "HasSuffix", Nothing),
    ("*", "equals", Nothing),
    ("*", "Equals", Nothing),
    ("*", "equalsIgnoreCase", Nothing),
    ("*", "eq", Nothing),
    ("*", "eql?", Nothing),
    ("*", "equal?", Nothing),
    ("*", "compareTo", Nothing),
    ("*", "compare", Nothing),
    ("*", "cmp", Nothing),
    ("*", "matches", Nothing),
    ("*", "match?", Nothing),
    ("*", "test", Nothing),
    ("*", "indexOf", Nothing),
    ("*", "lastIndexOf", Nothing),
    ("*", "IndexOf", Nothing),
    ("*", "index", Nothing),
    ("*", "Index", Nothing),
    ("*", "rindex", Nothing),
    ("*", "findIndex", Nothing),
    ("*", "position", Nothing),
    ("*", "some", Nothing),
    ("*", "every", Nothing),
    ("*", "all", Nothing),
    ("*", "any", Nothing),
    ("*", "all?", Nothing),
    ("*", "exists", Nothing),
    ("*", "Exists", Nothing),
    ("*", "hashCode", Nothing),
    ("*", "hash", Nothing),
    ("*", "close", Nothing),
    ("*", "Close", Nothing),
    ("*", "flush", Nothing),
    ("*", "Flush", Nothing),
    ("*", "wait", Nothing),
    ("*", "Wait", Nothing),
    ("*", "lock", Nothing),
    ("*", "Lock", Nothing),
    ("*", "unlock", Nothing),
    ("*", "Unlock", Nothing),
    ("*", "RLock", Nothing),
    ("*", "RUnlock", Nothing),
    ("*", "Done", Nothing),
    ("*", "Helper", Nothing),
    ("*", "Log", Nothing),
    ("*", "Logf", Nothing),
    ("*", "Errorf", Nothing),
    ("*", "Fatal", Nothing),
    ("*", "Fatalf", Nothing),
    ("*", "Skip", Nothing),
    ("*", "Skipf", Nothing),
    ("*", "Parallel", Nothing),
    ("*", "Cleanup", Nothing),
    ("*", "Run", Nothing),
    ("*", "log", Nothing),
    ("*", "info", Nothing),
    ("*", "debug", Nothing),
    ("*", "warn", Nothing),
    ("*", "warning", Nothing),
    ("*", "error", Nothing),
    ("*", "Info", Nothing),
    ("*", "Debug", Nothing),
    ("*", "Warn", Nothing),
    ("*", "Trace", Nothing),
    ("*", "Printf", Nothing),
    ("*", "Println", Nothing),
    ("*", "Print", Nothing),
    ("*", "print", Nothing),
    ("*", "println", Nothing),
    ("*", "printf", Nothing),
    ("*", "exception", Nothing),
    ("*", "Status", Nothing),
    ("*", "WriteHeader", Nothing),
    ("*", "SetHeader", Nothing),
    ("*", "setHeader", Nothing),
    ("*", "status", Nothing),
    ("*", "Set", Mutates),
    ("*", "Add", Mutates),
    ("*", "Del", Nothing),
    ("*", "Delete", Nothing),
    ("*", "delete", Nothing),
    ("*", "clear", Nothing),
    ("*", "Clear", Nothing),
    ("*", "Reset", Nothing),
    ("*", "reset", Nothing),
    ("*", "Now", Nothing),
    ("*", "Unix", Nothing),
    ("*", "UnixNano", Nothing),
    ("*", "Seconds", Nothing),
    ("*", "Milliseconds", Nothing),
    ("*", "Sub", Nothing),
    ("*", "Since", Nothing),
    ("*", "Before", Nothing),
    ("*", "After", Nothing),
    ("*", "IsZero", Nothing),
    ("*", "Time", Nothing),
    ("*", "Sleep", Nothing),
    ("*", "sleep", Nothing),
    // Mutators: the receiver is written from the arguments and returned.
    ("*", "append", Mutates),
    ("*", "Append", Mutates),
    ("*", "AppendLine", Mutates),
    ("*", "AppendFormat", Mutates),
    ("*", "push", Mutates),
    ("*", "Push", Mutates),
    ("*", "push_str", Mutates),
    ("*", "push_back", Mutates),
    ("*", "unshift", Mutates),
    ("*", "extend", Mutates),
    ("*", "extend_from_slice", Mutates),
    ("*", "insert", Mutates),
    ("*", "Insert", Mutates),
    ("*", "add", Mutates),
    ("*", "addAll", Mutates),
    ("*", "put", Mutates),
    ("*", "Put", Mutates),
    ("*", "putAll", Mutates),
    ("*", "putIfAbsent", Mutates),
    ("*", "set", Mutates),
    ("*", "setdefault", Mutates),
    ("*", "update", Mutates),
    ("*", "Update", Mutates),
    ("*", "merge", Mutates),
    ("*", "merge!", Mutates),
    ("*", "concat!", Mutates),
    ("*", "store", Mutates),
    ("*", "Store", Mutates),
    ("*", "write", Mutates),
    ("*", "Write", Mutates),
    ("*", "WriteString", Mutates),
    ("*", "WriteByte", Mutates),
    ("*", "WriteRune", Mutates),
    ("*", "write_str", Mutates),
    ("*", "write_all", Mutates),
    ("*", "writeln", Mutates),
    ("*", "puts", Mutates),
    ("*", "emit", Mutates),
    ("*", "fill", Mutates),
    ("*", "offer", Mutates),
    ("*", "enqueue", Mutates),
    ("*", "Enqueue", Mutates),
    ("*", "assign", Mutates),
    ("*", "replace_range", Mutates),
    ("*", "setAttribute", Mutates),
    ("*", "setValue", Mutates),
    ("*", "setText", Mutates),
    ("*", "setContent", Mutates),
    ("*", "setName", Mutates),
    ("*", "setPath", Mutates),
    ("*", "setHeaders", Mutates),
    ("*", "addHeader", Mutates),
    ("*", "SetContext", Mutates),
    ("*", "WithContext", RecvArgs),
    ("*", "With", RecvArgs),
    ("*", "WithField", RecvArgs),
    ("*", "WithFields", RecvArgs),
    ("*", "WithError", RecvArgs),
    ("*", "withColumn", RecvArgs),
    ("*", "Wrap", RecvArgs),
    ("*", "Wrapf", RecvArgs),
    ("*", "Sprintf", RecvArgs),
    ("*", "Sprint", RecvArgs),
    ("*", "Sprintln", RecvArgs),
    ("*", "Build", Recv),
    ("*", "build", Recv),
];

/// The summary for a call, if the table knows it.
///
/// `qualifier` is the receiver when it is a dotted name (a package or a
/// type); `has_receiver` says whether there is any receiver at all.
/// A summary the user adds for their own libraries, from
/// `.codegraph-summaries.json` at the source root — a JSON array of
/// objects: `{"name": "Sanitize", "shape": "Nothing"}` with optional
/// `"lang"` (default every language), `"qualifier"` (a package or type; the
/// entry then matches `qualifier.name`) and `"method": true` (matches
/// `anything.name`). Shapes are the [`Shape`] names. User entries are
/// consulted before the built-in tables.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UserSummary {
    pub lang: String,
    pub qualifier: Option<String>,
    pub method: bool,
    pub name: String,
    pub shape: Shape,
}

impl Shape {
    pub fn parse(s: &str) -> Option<Shape> {
        Some(match s {
            "Args" => Args,
            "RecvArgs" => RecvArgs,
            "Recv" => Recv,
            "Nothing" => Nothing,
            "External" => External,
            "Mutates" => Mutates,
            "WritesFirst" => WritesFirst,
            "WritesSecondFromFirst" => WritesSecondFromFirst,
            "FillsFirst" => FillsFirst,
            "FillsSecond" => FillsSecond,
            "FillsRest" => FillsRest,
            "WritesFirstFromRecv" => WritesFirstFromRecv,
            "WritesRestFromRecv" => WritesRestFromRecv,
            _ => return None,
        })
    }
}

static USER: std::sync::RwLock<Vec<UserSummary>> = std::sync::RwLock::new(Vec::new());

/// Install the user's summaries for this process; replaces any previous set.
pub fn install_user_summaries(entries: Vec<UserSummary>) {
    *USER.write().expect("summaries lock") = entries;
}

/// Parse the contents of a `.codegraph-summaries.json`. Malformed entries
/// are reported by index, not silently dropped.
pub fn parse_user_summaries(json: &str) -> std::result::Result<Vec<UserSummary>, String> {
    let raw: Vec<serde_json::Value> = serde_json::from_str(json).map_err(|e| format!("not a JSON array: {e}"))?;
    let mut out = Vec::new();
    for (i, v) in raw.iter().enumerate() {
        let name = v.get("name").and_then(|n| n.as_str()).ok_or_else(|| format!("entry {i}: missing \"name\""))?;
        let shape_s = v.get("shape").and_then(|n| n.as_str()).ok_or_else(|| format!("entry {i}: missing \"shape\""))?;
        let shape = Shape::parse(shape_s).ok_or_else(|| format!("entry {i}: unknown shape {shape_s:?}"))?;
        out.push(UserSummary {
            lang: v.get("lang").and_then(|n| n.as_str()).unwrap_or("*").to_string(),
            qualifier: v.get("qualifier").and_then(|n| n.as_str()).map(str::to_string),
            method: v.get("method").and_then(|n| n.as_bool()).unwrap_or(false),
            name: name.to_string(),
            shape,
        });
    }
    Ok(out)
}

/// Load `<root>/.codegraph-summaries.json` if present and install it.
/// Returns how many entries, or the parse error.
pub fn load_user_summaries(root: &std::path::Path) -> std::result::Result<usize, String> {
    let path = root.join(".codegraph-summaries.json");
    let Ok(text) = std::fs::read_to_string(&path) else {
        install_user_summaries(Vec::new());
        return Ok(0);
    };
    let entries = parse_user_summaries(&text).map_err(|e| format!("{}: {e}", path.display()))?;
    let n = entries.len();
    install_user_summaries(entries);
    Ok(n)
}

pub fn lookup(lang: &str, qualifier: Option<&str>, has_receiver: bool, name: &str) -> Option<Summary> {
    // The user's entries first: they know their libraries.
    if let Ok(user) = USER.read()
        && !user.is_empty()
    {
        let last = qualifier.map(|q| q.rsplit(['.', ':']).next().unwrap_or(q));
        for u in user.iter() {
            if u.name != name || !lang_matches(&u.lang, lang) {
                continue;
            }
            let hit = match (&u.qualifier, u.method) {
                (Some(q), _) => qualifier == Some(q.as_str()) || last == Some(q.as_str()),
                (None, true) => has_receiver,
                (None, false) => !has_receiver,
            };
            if hit {
                return Some(Summary::of(u.shape));
            }
        }
    }
    if let Some(q) = qualifier {
        // The full qualifier first (`os.path`), then its last segment
        // (`path`, for `filepath.Join` written as `filepath`).
        let last = q.rsplit(['.', ':']).next().unwrap_or(q);
        for (langs, qq, n, shape) in QUALIFIED {
            if (*qq == q || *qq == last) && *n == name && lang_matches(langs, lang) {
                return Some(Summary::of(*shape));
            }
        }
    }
    if has_receiver {
        for (langs, n, shape) in METHODS {
            if *n == name && lang_matches(langs, lang) {
                return Some(Summary::of(*shape));
            }
        }
        return None;
    }
    for (langs, n, shape) in BARE {
        if *n == name && lang_matches(langs, lang) {
            return Some(Summary::of(*shape));
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn qualified_beats_method_beats_bare() {
        assert_eq!(lookup("go", Some("fmt"), true, "Sprintf").unwrap().result, &[Slot::Rest(0)]);
        assert_eq!(lookup("go", Some("filepath"), true, "Join").unwrap().result, &[Slot::Rest(0)]);
        assert_eq!(lookup("python", Some("os.path"), true, "join").unwrap().result, &[Slot::Rest(0)]);
        // A method on some receiver: `x.append(y)` mutates `x`.
        let m = lookup("python", Some("self.items"), true, "append").unwrap();
        assert_eq!(m.writes, &[(Slot::Recv, &[Slot::Rest(0)][..])]);
        // A bare C call.
        assert_eq!(lookup("c", None, false, "strcpy").unwrap().result, &[Slot::Arg(0)]);
        assert!(lookup("c", None, false, "fgets").unwrap().external());
        // Language scoping.
        assert!(lookup("python", None, false, "strcpy").is_none());
        assert!(lookup("cpp", None, false, "strcpy").is_some());
        assert!(lookup("tsx", Some("JSON"), true, "parse").is_some());
        // Unknown names keep the default.
        assert!(lookup("go", Some("mypkg"), true, "Frobnicate").is_none());
        assert!(lookup("go", None, false, "frobnicate").is_none());
    }

    #[test]
    fn nothing_and_external_are_distinct() {
        assert!(lookup("go", Some("assert"), true, "Equal").unwrap().result.is_empty());
        assert!(!lookup("go", Some("assert"), true, "Equal").unwrap().external());
        assert!(lookup("go", Some("os"), true, "Getenv").unwrap().external());
    }
}
